// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

package schedulerproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AcquireContainerRequest struct {
	FunctionName         string          `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	FunctionConfig       *FunctionConfig `protobuf:"bytes,2,opt,name=function_config,json=functionConfig,proto3" json:"function_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AcquireContainerRequest) Reset()         { *m = AcquireContainerRequest{} }
func (m *AcquireContainerRequest) String() string { return proto.CompactTextString(m) }
func (*AcquireContainerRequest) ProtoMessage()    {}
func (*AcquireContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

func (m *AcquireContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcquireContainerRequest.Unmarshal(m, b)
}
func (m *AcquireContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcquireContainerRequest.Marshal(b, m, deterministic)
}
func (m *AcquireContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcquireContainerRequest.Merge(m, src)
}
func (m *AcquireContainerRequest) XXX_Size() int {
	return xxx_messageInfo_AcquireContainerRequest.Size(m)
}
func (m *AcquireContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcquireContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcquireContainerRequest proto.InternalMessageInfo

func (m *AcquireContainerRequest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *AcquireContainerRequest) GetFunctionConfig() *FunctionConfig {
	if m != nil {
		return m.FunctionConfig
	}
	return nil
}

type AcquireContainerReply struct {
	Container            *Container `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AcquireContainerReply) Reset()         { *m = AcquireContainerReply{} }
func (m *AcquireContainerReply) String() string { return proto.CompactTextString(m) }
func (*AcquireContainerReply) ProtoMessage()    {}
func (*AcquireContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1}
}

func (m *AcquireContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcquireContainerReply.Unmarshal(m, b)
}
func (m *AcquireContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcquireContainerReply.Marshal(b, m, deterministic)
}
func (m *AcquireContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcquireContainerReply.Merge(m, src)
}
func (m *AcquireContainerReply) XXX_Size() int {
	return xxx_messageInfo_AcquireContainerReply.Size(m)
}
func (m *AcquireContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AcquireContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_AcquireContainerReply proto.InternalMessageInfo

func (m *AcquireContainerReply) GetContainer() *Container {
	if m != nil {
		return m.Container
	}
	return nil
}

type ReturnContainerRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerStatus      string   `protobuf:"bytes,2,opt,name=container_status,json=containerStatus,proto3" json:"container_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnContainerRequest) Reset()         { *m = ReturnContainerRequest{} }
func (m *ReturnContainerRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnContainerRequest) ProtoMessage()    {}
func (*ReturnContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2}
}

func (m *ReturnContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnContainerRequest.Unmarshal(m, b)
}
func (m *ReturnContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnContainerRequest.Marshal(b, m, deterministic)
}
func (m *ReturnContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnContainerRequest.Merge(m, src)
}
func (m *ReturnContainerRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnContainerRequest.Size(m)
}
func (m *ReturnContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnContainerRequest proto.InternalMessageInfo

func (m *ReturnContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ReturnContainerRequest) GetContainerStatus() string {
	if m != nil {
		return m.ContainerStatus
	}
	return ""
}

type ReturnContainerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnContainerReply) Reset()         { *m = ReturnContainerReply{} }
func (m *ReturnContainerReply) String() string { return proto.CompactTextString(m) }
func (*ReturnContainerReply) ProtoMessage()    {}
func (*ReturnContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{3}
}

func (m *ReturnContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnContainerReply.Unmarshal(m, b)
}
func (m *ReturnContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnContainerReply.Marshal(b, m, deterministic)
}
func (m *ReturnContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnContainerReply.Merge(m, src)
}
func (m *ReturnContainerReply) XXX_Size() int {
	return xxx_messageInfo_ReturnContainerReply.Size(m)
}
func (m *ReturnContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnContainerReply proto.InternalMessageInfo

type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	IsBusy               bool     `protobuf:"varint,4,opt,name=is_busy,json=isBusy,proto3" json:"is_busy,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{4}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Container) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Container) GetIsBusy() bool {
	if m != nil {
		return m.IsBusy
	}
	return false
}

func (m *Container) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type FunctionConfig struct {
	Timeout              int32    `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MemoryMb             int32    `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Handler              string   `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionConfig) Reset()         { *m = FunctionConfig{} }
func (m *FunctionConfig) String() string { return proto.CompactTextString(m) }
func (*FunctionConfig) ProtoMessage()    {}
func (*FunctionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{5}
}

func (m *FunctionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionConfig.Unmarshal(m, b)
}
func (m *FunctionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionConfig.Marshal(b, m, deterministic)
}
func (m *FunctionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionConfig.Merge(m, src)
}
func (m *FunctionConfig) XXX_Size() int {
	return xxx_messageInfo_FunctionConfig.Size(m)
}
func (m *FunctionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionConfig proto.InternalMessageInfo

func (m *FunctionConfig) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *FunctionConfig) GetMemoryMb() int32 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *FunctionConfig) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func init() {
	proto.RegisterType((*AcquireContainerRequest)(nil), "schedulerproto.AcquireContainerRequest")
	proto.RegisterType((*AcquireContainerReply)(nil), "schedulerproto.AcquireContainerReply")
	proto.RegisterType((*ReturnContainerRequest)(nil), "schedulerproto.ReturnContainerRequest")
	proto.RegisterType((*ReturnContainerReply)(nil), "schedulerproto.ReturnContainerReply")
	proto.RegisterType((*Container)(nil), "schedulerproto.Container")
	proto.RegisterType((*FunctionConfig)(nil), "schedulerproto.FunctionConfig")
}

func init() {
	proto.RegisterFile("scheduler.proto", fileDescriptor_2b3fc28395a6d9c5)
}

var fileDescriptor_2b3fc28395a6d9c5 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0x65, 0xd3, 0xdd, 0x4c, 0x97, 0x64, 0x65, 0xc1, 0x6e, 0x58, 0x24, 0x14, 0xc2, 0x57,
	0xb8, 0xf4, 0x50, 0x0e, 0x9c, 0x61, 0x25, 0xd0, 0x1e, 0x40, 0xc8, 0xfd, 0x01, 0x91, 0x13, 0x3b,
	0xd4, 0x52, 0x62, 0xa7, 0xfe, 0x38, 0x44, 0xfc, 0x00, 0xfe, 0x20, 0x3f, 0x08, 0xc5, 0x34, 0xa9,
	0x9a, 0x82, 0x7a, 0xcb, 0x7b, 0x7e, 0x33, 0xef, 0xcd, 0x4c, 0x20, 0xd2, 0xe5, 0x86, 0x51, 0x5b,
	0x33, 0xb5, 0x6c, 0x95, 0x34, 0x12, 0x85, 0x23, 0xe1, 0x70, 0xfa, 0xcb, 0x83, 0x9b, 0x8f, 0xe5,
	0xd6, 0x72, 0xc5, 0xee, 0xa4, 0x30, 0x84, 0x0b, 0xa6, 0x30, 0xdb, 0x5a, 0xa6, 0x0d, 0x7a, 0x09,
	0x8f, 0x2a, 0x2b, 0x4a, 0xc3, 0xa5, 0xc8, 0x05, 0x69, 0x58, 0xec, 0x25, 0x5e, 0x16, 0xe0, 0xcb,
	0x81, 0xfc, 0x46, 0x1a, 0x86, 0xbe, 0x40, 0x34, 0x8a, 0x4a, 0x29, 0x2a, 0xfe, 0x23, 0x9e, 0x25,
	0x5e, 0xb6, 0x58, 0x3d, 0x5f, 0x1e, 0x5a, 0x2d, 0x3f, 0xef, 0x64, 0x77, 0x4e, 0x85, 0xc3, 0xea,
	0x00, 0xa7, 0xdf, 0xe1, 0xc9, 0x71, 0x90, 0xb6, 0xee, 0xd0, 0x07, 0x08, 0xca, 0x81, 0x71, 0x11,
	0x16, 0xab, 0xa7, 0xd3, 0xde, 0xfb, 0x92, 0xbd, 0x36, 0xad, 0xe0, 0x1a, 0x33, 0x63, 0x95, 0x38,
	0x9a, 0xec, 0x05, 0x5c, 0x8e, 0xb2, 0x9c, 0xd3, 0xdd, 0x60, 0x8b, 0x91, 0xbb, 0xa7, 0xe8, 0x1d,
	0x5c, 0xed, 0x25, 0xda, 0x10, 0x63, 0xb5, 0x1b, 0x2c, 0xc0, 0xd1, 0xc8, 0xaf, 0x1d, 0x9d, 0x5e,
	0xc3, 0xe3, 0x23, 0x9f, 0xb6, 0xee, 0xd2, 0x9f, 0x10, 0x8c, 0x0c, 0x0a, 0x61, 0x36, 0x1a, 0xcd,
	0x38, 0x45, 0x31, 0x9c, 0x13, 0x4a, 0x15, 0xd3, 0x43, 0xdb, 0x01, 0x22, 0x04, 0x67, 0xad, 0x54,
	0x26, 0x7e, 0x98, 0x78, 0x99, 0x8f, 0xdd, 0x37, 0xba, 0x81, 0x73, 0xae, 0xf3, 0xc2, 0xea, 0x2e,
	0x3e, 0x4b, 0xbc, 0xec, 0x02, 0xcf, 0xb9, 0xfe, 0x64, 0x75, 0xd7, 0x3f, 0x08, 0x49, 0x59, 0x3f,
	0x84, 0xef, 0xda, 0xcc, 0x7b, 0x78, 0x4f, 0x53, 0x02, 0xe1, 0xe1, 0xc2, 0x7b, 0x47, 0xc3, 0x1b,
	0x26, 0xad, 0x71, 0x31, 0x7c, 0x3c, 0x40, 0xf4, 0x0c, 0x82, 0x86, 0x35, 0x52, 0x75, 0x79, 0x53,
	0xb8, 0x34, 0x3e, 0xbe, 0xf8, 0x4b, 0x7c, 0x2d, 0xfa, 0xb2, 0x0d, 0x11, 0xb4, 0x66, 0xca, 0x25,
	0x0a, 0xf0, 0x00, 0x57, 0xbf, 0x3d, 0x08, 0xd6, 0xc3, 0x1d, 0x10, 0x85, 0xab, 0xe9, 0xfd, 0xd0,
	0xdb, 0xe9, 0x9d, 0xfe, 0xf3, 0xab, 0xdd, 0xbe, 0x3e, 0x2d, 0xec, 0x37, 0xfa, 0x00, 0x11, 0x88,
	0x26, 0xbb, 0x46, 0x6f, 0xa6, 0xb5, 0xff, 0x3e, 0xfa, 0xed, 0xab, 0x93, 0x3a, 0x67, 0x51, 0xcc,
	0xdd, 0xeb, 0xfb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x3e, 0xb5, 0x5f, 0x3c, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	AcquireContainer(ctx context.Context, in *AcquireContainerRequest, opts ...grpc.CallOption) (*AcquireContainerReply, error)
	ReturnContainer(ctx context.Context, in *ReturnContainerRequest, opts ...grpc.CallOption) (*ReturnContainerReply, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) AcquireContainer(ctx context.Context, in *AcquireContainerRequest, opts ...grpc.CallOption) (*AcquireContainerReply, error) {
	out := new(AcquireContainerReply)
	err := c.cc.Invoke(ctx, "/schedulerproto.Scheduler/AcquireContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ReturnContainer(ctx context.Context, in *ReturnContainerRequest, opts ...grpc.CallOption) (*ReturnContainerReply, error) {
	out := new(ReturnContainerReply)
	err := c.cc.Invoke(ctx, "/schedulerproto.Scheduler/ReturnContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	AcquireContainer(context.Context, *AcquireContainerRequest) (*AcquireContainerReply, error)
	ReturnContainer(context.Context, *ReturnContainerRequest) (*ReturnContainerReply, error)
}

// UnimplementedSchedulerServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) AcquireContainer(ctx context.Context, req *AcquireContainerRequest) (*AcquireContainerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireContainer not implemented")
}
func (*UnimplementedSchedulerServer) ReturnContainer(ctx context.Context, req *ReturnContainerRequest) (*ReturnContainerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnContainer not implemented")
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_AcquireContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).AcquireContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedulerproto.Scheduler/AcquireContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).AcquireContainer(ctx, req.(*AcquireContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ReturnContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ReturnContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedulerproto.Scheduler/ReturnContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ReturnContainer(ctx, req.(*ReturnContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schedulerproto.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireContainer",
			Handler:    _Scheduler_AcquireContainer_Handler,
		},
		{
			MethodName: "ReturnContainer",
			Handler:    _Scheduler_ReturnContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
