// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

package schedulerproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AcquireContainerRequest struct {
	AccountId            string          `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FunctionName         string          `protobuf:"bytes,2,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	FunctionConfig       *FunctionConfig `protobuf:"bytes,3,opt,name=function_config,json=functionConfig,proto3" json:"function_config,omitempty"`
	RequestId            string          `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AcquireContainerRequest) Reset()         { *m = AcquireContainerRequest{} }
func (m *AcquireContainerRequest) String() string { return proto.CompactTextString(m) }
func (*AcquireContainerRequest) ProtoMessage()    {}
func (*AcquireContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{0}
}

func (m *AcquireContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcquireContainerRequest.Unmarshal(m, b)
}
func (m *AcquireContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcquireContainerRequest.Marshal(b, m, deterministic)
}
func (m *AcquireContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcquireContainerRequest.Merge(m, src)
}
func (m *AcquireContainerRequest) XXX_Size() int {
	return xxx_messageInfo_AcquireContainerRequest.Size(m)
}
func (m *AcquireContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AcquireContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AcquireContainerRequest proto.InternalMessageInfo

func (m *AcquireContainerRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *AcquireContainerRequest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *AcquireContainerRequest) GetFunctionConfig() *FunctionConfig {
	if m != nil {
		return m.FunctionConfig
	}
	return nil
}

func (m *AcquireContainerRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type AcquireContainerReply struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeAddress          string   `protobuf:"bytes,2,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodeServicePort      int32    `protobuf:"varint,3,opt,name=node_service_port,json=nodeServicePort,proto3" json:"node_service_port,omitempty"`
	ContainerId          string   `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AcquireContainerReply) Reset()         { *m = AcquireContainerReply{} }
func (m *AcquireContainerReply) String() string { return proto.CompactTextString(m) }
func (*AcquireContainerReply) ProtoMessage()    {}
func (*AcquireContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{1}
}

func (m *AcquireContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AcquireContainerReply.Unmarshal(m, b)
}
func (m *AcquireContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AcquireContainerReply.Marshal(b, m, deterministic)
}
func (m *AcquireContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AcquireContainerReply.Merge(m, src)
}
func (m *AcquireContainerReply) XXX_Size() int {
	return xxx_messageInfo_AcquireContainerReply.Size(m)
}
func (m *AcquireContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AcquireContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_AcquireContainerReply proto.InternalMessageInfo

func (m *AcquireContainerReply) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *AcquireContainerReply) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *AcquireContainerReply) GetNodeServicePort() int32 {
	if m != nil {
		return m.NodeServicePort
	}
	return 0
}

func (m *AcquireContainerReply) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type ReturnContainerRequest struct {
	RequestId             string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ContainerId           string   `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	DurationInNanos       int64    `protobuf:"varint,3,opt,name=duration_in_nanos,json=durationInNanos,proto3" json:"duration_in_nanos,omitempty"`
	MaxMemoryUsageInBytes int64    `protobuf:"varint,4,opt,name=max_memory_usage_in_bytes,json=maxMemoryUsageInBytes,proto3" json:"max_memory_usage_in_bytes,omitempty"`
	ErrorCode             string   `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage          string   `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *ReturnContainerRequest) Reset()         { *m = ReturnContainerRequest{} }
func (m *ReturnContainerRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnContainerRequest) ProtoMessage()    {}
func (*ReturnContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{2}
}

func (m *ReturnContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnContainerRequest.Unmarshal(m, b)
}
func (m *ReturnContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnContainerRequest.Marshal(b, m, deterministic)
}
func (m *ReturnContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnContainerRequest.Merge(m, src)
}
func (m *ReturnContainerRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnContainerRequest.Size(m)
}
func (m *ReturnContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnContainerRequest proto.InternalMessageInfo

func (m *ReturnContainerRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *ReturnContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ReturnContainerRequest) GetDurationInNanos() int64 {
	if m != nil {
		return m.DurationInNanos
	}
	return 0
}

func (m *ReturnContainerRequest) GetMaxMemoryUsageInBytes() int64 {
	if m != nil {
		return m.MaxMemoryUsageInBytes
	}
	return 0
}

func (m *ReturnContainerRequest) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *ReturnContainerRequest) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ReturnContainerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnContainerReply) Reset()         { *m = ReturnContainerReply{} }
func (m *ReturnContainerReply) String() string { return proto.CompactTextString(m) }
func (*ReturnContainerReply) ProtoMessage()    {}
func (*ReturnContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{3}
}

func (m *ReturnContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnContainerReply.Unmarshal(m, b)
}
func (m *ReturnContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnContainerReply.Marshal(b, m, deterministic)
}
func (m *ReturnContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnContainerReply.Merge(m, src)
}
func (m *ReturnContainerReply) XXX_Size() int {
	return xxx_messageInfo_ReturnContainerReply.Size(m)
}
func (m *ReturnContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnContainerReply proto.InternalMessageInfo

type FunctionConfig struct {
	TimeoutInSecs        int32    `protobuf:"varint,1,opt,name=timeout_in_secs,json=timeoutInSecs,proto3" json:"timeout_in_secs,omitempty"`
	MemoryInBytes        int32    `protobuf:"varint,2,opt,name=memory_in_bytes,json=memoryInBytes,proto3" json:"memory_in_bytes,omitempty"`
	Handler              string   `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionConfig) Reset()         { *m = FunctionConfig{} }
func (m *FunctionConfig) String() string { return proto.CompactTextString(m) }
func (*FunctionConfig) ProtoMessage()    {}
func (*FunctionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b3fc28395a6d9c5, []int{4}
}

func (m *FunctionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionConfig.Unmarshal(m, b)
}
func (m *FunctionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionConfig.Marshal(b, m, deterministic)
}
func (m *FunctionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionConfig.Merge(m, src)
}
func (m *FunctionConfig) XXX_Size() int {
	return xxx_messageInfo_FunctionConfig.Size(m)
}
func (m *FunctionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionConfig proto.InternalMessageInfo

func (m *FunctionConfig) GetTimeoutInSecs() int32 {
	if m != nil {
		return m.TimeoutInSecs
	}
	return 0
}

func (m *FunctionConfig) GetMemoryInBytes() int32 {
	if m != nil {
		return m.MemoryInBytes
	}
	return 0
}

func (m *FunctionConfig) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func init() {
	proto.RegisterType((*AcquireContainerRequest)(nil), "schedulerproto.AcquireContainerRequest")
	proto.RegisterType((*AcquireContainerReply)(nil), "schedulerproto.AcquireContainerReply")
	proto.RegisterType((*ReturnContainerRequest)(nil), "schedulerproto.ReturnContainerRequest")
	proto.RegisterType((*ReturnContainerReply)(nil), "schedulerproto.ReturnContainerReply")
	proto.RegisterType((*FunctionConfig)(nil), "schedulerproto.FunctionConfig")
}

func init() {
	proto.RegisterFile("scheduler.proto", fileDescriptor_2b3fc28395a6d9c5)
}

var fileDescriptor_2b3fc28395a6d9c5 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0x42, 0x52, 0x65, 0xd2, 0xc6, 0xb0, 0xa2, 0xad, 0xa9, 0x04, 0x2a, 0x06, 0x4a,
	0xc5, 0x21, 0x87, 0x72, 0xe1, 0x5a, 0x22, 0x81, 0x7c, 0x68, 0x85, 0x1c, 0x71, 0xb6, 0xb6, 0xbb,
	0x93, 0xd6, 0x52, 0xbc, 0x9b, 0xee, 0x1f, 0xd4, 0x70, 0xe6, 0x49, 0x78, 0x17, 0xde, 0x80, 0x07,
	0x42, 0xbb, 0x6b, 0xa7, 0xc4, 0x29, 0xca, 0x71, 0xbe, 0xef, 0xdb, 0xdd, 0xdf, 0x8c, 0xc7, 0x10,
	0x6b, 0x76, 0x83, 0xdc, 0xce, 0x51, 0x8d, 0x17, 0x4a, 0x1a, 0x49, 0x46, 0x2b, 0xc1, 0xd7, 0xe9,
	0xef, 0x08, 0x0e, 0xcf, 0xd9, 0xad, 0x2d, 0x15, 0x4e, 0xa4, 0x30, 0xb4, 0x14, 0xa8, 0x72, 0xbc,
	0xb5, 0xa8, 0x0d, 0x79, 0x01, 0x40, 0x19, 0x93, 0x56, 0x98, 0xa2, 0xe4, 0x49, 0x74, 0x1c, 0x9d,
	0x0e, 0xf2, 0x41, 0xad, 0x64, 0x9c, 0xbc, 0x86, 0xbd, 0x99, 0x15, 0xcc, 0x94, 0x52, 0x14, 0x82,
	0x56, 0x98, 0x74, 0x7c, 0x62, 0xb7, 0x11, 0x2f, 0x69, 0x85, 0xe4, 0x0b, 0xc4, 0xab, 0x10, 0x93,
	0x62, 0x56, 0x5e, 0x27, 0xdd, 0xe3, 0xe8, 0x74, 0x78, 0xf6, 0x72, 0xbc, 0x4e, 0x32, 0xfe, 0x5c,
	0xc7, 0x26, 0x3e, 0x95, 0x8f, 0x66, 0x6b, 0xb5, 0x83, 0x51, 0x81, 0xcb, 0xc1, 0x3c, 0x0e, 0x30,
	0xb5, 0x92, 0xf1, 0xf4, 0x57, 0x04, 0xfb, 0x9b, 0x7d, 0x2c, 0xe6, 0x4b, 0x72, 0x08, 0x3b, 0x42,
	0x72, 0xbc, 0x6f, 0xa1, 0xef, 0xca, 0x8c, 0x93, 0x57, 0xb0, 0xeb, 0x0d, 0xca, 0xb9, 0x42, 0xad,
	0x6b, 0xfc, 0xa1, 0xd3, 0xce, 0x83, 0x44, 0xde, 0xc3, 0x53, 0x1f, 0xd1, 0xa8, 0xbe, 0x97, 0x0c,
	0x8b, 0x85, 0x54, 0xc6, 0xf3, 0xf7, 0xf2, 0xd8, 0x19, 0xd3, 0xa0, 0x7f, 0x95, 0xca, 0xb8, 0xeb,
	0x58, 0xf3, 0xf2, 0x3d, 0xe2, 0x70, 0xa5, 0x65, 0x3c, 0xfd, 0xd9, 0x81, 0x83, 0x1c, 0x8d, 0x55,
	0xe2, 0xa1, 0x59, 0xff, 0xd3, 0x5e, 0xd4, 0x6a, 0x6f, 0xe3, 0xf2, 0xce, 0xc6, 0xe5, 0x8e, 0x95,
	0x5b, 0x45, 0xfd, 0xa4, 0x4b, 0xf7, 0x45, 0x84, 0xd4, 0x9e, 0xb5, 0x9b, 0xc7, 0x8d, 0x91, 0x89,
	0x4b, 0x27, 0x93, 0x8f, 0xf0, 0xbc, 0xa2, 0x77, 0x45, 0x85, 0x95, 0x54, 0xcb, 0xc2, 0x6a, 0x7a,
	0x8d, 0xee, 0xcc, 0xd5, 0xd2, 0xa0, 0xf6, 0xe0, 0xdd, 0x7c, 0xbf, 0xa2, 0x77, 0x17, 0xde, 0xff,
	0xe6, 0xec, 0x4c, 0x7c, 0x72, 0xa6, 0xe3, 0x44, 0xa5, 0xa4, 0x2a, 0x98, 0xe4, 0x98, 0xf4, 0x02,
	0xa7, 0x57, 0x26, 0x92, 0xa3, 0xdb, 0x89, 0x60, 0x57, 0xa8, 0xdd, 0xb1, 0xa4, 0x1f, 0x76, 0xc2,
	0x8b, 0x17, 0x41, 0x4b, 0x0f, 0xe0, 0xd9, 0xc6, 0x14, 0x16, 0xf3, 0x65, 0xfa, 0x03, 0x46, 0xeb,
	0x4b, 0x40, 0x4e, 0x20, 0x36, 0x65, 0x85, 0xd2, 0x1a, 0x87, 0xa7, 0x91, 0x69, 0x3f, 0x9a, 0x5e,
	0xbe, 0x57, 0xcb, 0x99, 0x98, 0x22, 0xd3, 0x2e, 0x57, 0xf7, 0xb2, 0xea, 0xa2, 0x13, 0x72, 0x41,
	0x6e, 0xe8, 0x13, 0xd8, 0xb9, 0xa1, 0x82, 0xcf, 0x51, 0xf9, 0xc9, 0x0c, 0xf2, 0xa6, 0x3c, 0xfb,
	0x13, 0xc1, 0x60, 0xda, 0x2c, 0x24, 0xe1, 0xf0, 0xa4, 0xbd, 0x4c, 0xe4, 0x5d, 0x7b, 0x61, 0xff,
	0xf3, 0xdb, 0x1c, 0xbd, 0xdd, 0x1e, 0x74, 0xdd, 0x3e, 0x22, 0x14, 0xe2, 0xd6, 0x1c, 0xc8, 0x49,
	0xfb, 0xec, 0xc3, 0xeb, 0x72, 0xf4, 0x66, 0x6b, 0xce, 0x3f, 0x71, 0xd5, 0xf7, 0xee, 0x87, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x75, 0x28, 0xef, 0xfe, 0x08, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedulerClient interface {
	AcquireContainer(ctx context.Context, in *AcquireContainerRequest, opts ...grpc.CallOption) (*AcquireContainerReply, error)
	ReturnContainer(ctx context.Context, in *ReturnContainerRequest, opts ...grpc.CallOption) (*ReturnContainerReply, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) AcquireContainer(ctx context.Context, in *AcquireContainerRequest, opts ...grpc.CallOption) (*AcquireContainerReply, error) {
	out := new(AcquireContainerReply)
	err := c.cc.Invoke(ctx, "/schedulerproto.Scheduler/AcquireContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulerClient) ReturnContainer(ctx context.Context, in *ReturnContainerRequest, opts ...grpc.CallOption) (*ReturnContainerReply, error) {
	out := new(ReturnContainerReply)
	err := c.cc.Invoke(ctx, "/schedulerproto.Scheduler/ReturnContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
type SchedulerServer interface {
	AcquireContainer(context.Context, *AcquireContainerRequest) (*AcquireContainerReply, error)
	ReturnContainer(context.Context, *ReturnContainerRequest) (*ReturnContainerReply, error)
}

// UnimplementedSchedulerServer can be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) AcquireContainer(ctx context.Context, req *AcquireContainerRequest) (*AcquireContainerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireContainer not implemented")
}
func (*UnimplementedSchedulerServer) ReturnContainer(ctx context.Context, req *ReturnContainerRequest) (*ReturnContainerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnContainer not implemented")
}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_AcquireContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).AcquireContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedulerproto.Scheduler/AcquireContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).AcquireContainer(ctx, req.(*AcquireContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scheduler_ReturnContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ReturnContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedulerproto.Scheduler/ReturnContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ReturnContainer(ctx, req.(*ReturnContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schedulerproto.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AcquireContainer",
			Handler:    _Scheduler_AcquireContainer_Handler,
		},
		{
			MethodName: "ReturnContainer",
			Handler:    _Scheduler_ReturnContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler.proto",
}
