// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node_service.proto

package nodeservoceproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FunctionMeta struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Handler              string   `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	TimeoutInSecs        int32    `protobuf:"varint,3,opt,name=timeout_in_secs,json=timeoutInSecs,proto3" json:"timeout_in_secs,omitempty"`
	MemoryInBytes        int64    `protobuf:"varint,4,opt,name=memory_in_bytes,json=memoryInBytes,proto3" json:"memory_in_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionMeta) Reset()         { *m = FunctionMeta{} }
func (m *FunctionMeta) String() string { return proto.CompactTextString(m) }
func (*FunctionMeta) ProtoMessage()    {}
func (*FunctionMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{0}
}

func (m *FunctionMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionMeta.Unmarshal(m, b)
}
func (m *FunctionMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionMeta.Marshal(b, m, deterministic)
}
func (m *FunctionMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionMeta.Merge(m, src)
}
func (m *FunctionMeta) XXX_Size() int {
	return xxx_messageInfo_FunctionMeta.Size(m)
}
func (m *FunctionMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionMeta.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionMeta proto.InternalMessageInfo

func (m *FunctionMeta) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *FunctionMeta) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func (m *FunctionMeta) GetTimeoutInSecs() int32 {
	if m != nil {
		return m.TimeoutInSecs
	}
	return 0
}

func (m *FunctionMeta) GetMemoryInBytes() int64 {
	if m != nil {
		return m.MemoryInBytes
	}
	return 0
}

type CreateContainerRequest struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FunctionMeta         *FunctionMeta `protobuf:"bytes,2,opt,name=function_meta,json=functionMeta,proto3" json:"function_meta,omitempty"`
	RequestId            string        `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateContainerRequest) Reset()         { *m = CreateContainerRequest{} }
func (m *CreateContainerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateContainerRequest) ProtoMessage()    {}
func (*CreateContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{1}
}

func (m *CreateContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerRequest.Unmarshal(m, b)
}
func (m *CreateContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerRequest.Marshal(b, m, deterministic)
}
func (m *CreateContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerRequest.Merge(m, src)
}
func (m *CreateContainerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateContainerRequest.Size(m)
}
func (m *CreateContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerRequest proto.InternalMessageInfo

func (m *CreateContainerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateContainerRequest) GetFunctionMeta() *FunctionMeta {
	if m != nil {
		return m.FunctionMeta
	}
	return nil
}

func (m *CreateContainerRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type CreateContainerReply struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateContainerReply) Reset()         { *m = CreateContainerReply{} }
func (m *CreateContainerReply) String() string { return proto.CompactTextString(m) }
func (*CreateContainerReply) ProtoMessage()    {}
func (*CreateContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{2}
}

func (m *CreateContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateContainerReply.Unmarshal(m, b)
}
func (m *CreateContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateContainerReply.Marshal(b, m, deterministic)
}
func (m *CreateContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateContainerReply.Merge(m, src)
}
func (m *CreateContainerReply) XXX_Size() int {
	return xxx_messageInfo_CreateContainerReply.Size(m)
}
func (m *CreateContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateContainerReply proto.InternalMessageInfo

func (m *CreateContainerReply) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

type RemoveContainerRequest struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	RequestId            string   `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContainerRequest) Reset()         { *m = RemoveContainerRequest{} }
func (m *RemoveContainerRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveContainerRequest) ProtoMessage()    {}
func (*RemoveContainerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{3}
}

func (m *RemoveContainerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContainerRequest.Unmarshal(m, b)
}
func (m *RemoveContainerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContainerRequest.Marshal(b, m, deterministic)
}
func (m *RemoveContainerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContainerRequest.Merge(m, src)
}
func (m *RemoveContainerRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveContainerRequest.Size(m)
}
func (m *RemoveContainerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContainerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContainerRequest proto.InternalMessageInfo

func (m *RemoveContainerRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *RemoveContainerRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type RemoveContainerReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveContainerReply) Reset()         { *m = RemoveContainerReply{} }
func (m *RemoveContainerReply) String() string { return proto.CompactTextString(m) }
func (*RemoveContainerReply) ProtoMessage()    {}
func (*RemoveContainerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{4}
}

func (m *RemoveContainerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveContainerReply.Unmarshal(m, b)
}
func (m *RemoveContainerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveContainerReply.Marshal(b, m, deterministic)
}
func (m *RemoveContainerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveContainerReply.Merge(m, src)
}
func (m *RemoveContainerReply) XXX_Size() int {
	return xxx_messageInfo_RemoveContainerReply.Size(m)
}
func (m *RemoveContainerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveContainerReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveContainerReply proto.InternalMessageInfo

type InvokeFunctionRequest struct {
	ContainerId          string        `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Event                []byte        `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	FunctionMeta         *FunctionMeta `protobuf:"bytes,3,opt,name=function_meta,json=functionMeta,proto3" json:"function_meta,omitempty"`
	RequestId            string        `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InvokeFunctionRequest) Reset()         { *m = InvokeFunctionRequest{} }
func (m *InvokeFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionRequest) ProtoMessage()    {}
func (*InvokeFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{5}
}

func (m *InvokeFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionRequest.Unmarshal(m, b)
}
func (m *InvokeFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionRequest.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionRequest.Merge(m, src)
}
func (m *InvokeFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionRequest.Size(m)
}
func (m *InvokeFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionRequest proto.InternalMessageInfo

func (m *InvokeFunctionRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *InvokeFunctionRequest) GetFunctionMeta() *FunctionMeta {
	if m != nil {
		return m.FunctionMeta
	}
	return nil
}

func (m *InvokeFunctionRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type InvokeFunctionReply struct {
	Body                 []byte                      `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Header               *InvokeFunctionReply_Header `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Footer               *InvokeFunctionReply_Footer `protobuf:"bytes,3,opt,name=footer,proto3" json:"footer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InvokeFunctionReply) Reset()         { *m = InvokeFunctionReply{} }
func (m *InvokeFunctionReply) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply) ProtoMessage()    {}
func (*InvokeFunctionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{6}
}

func (m *InvokeFunctionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply.Unmarshal(m, b)
}
func (m *InvokeFunctionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply.Merge(m, src)
}
func (m *InvokeFunctionReply) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply.Size(m)
}
func (m *InvokeFunctionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply proto.InternalMessageInfo

func (m *InvokeFunctionReply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *InvokeFunctionReply) GetHeader() *InvokeFunctionReply_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InvokeFunctionReply) GetFooter() *InvokeFunctionReply_Footer {
	if m != nil {
		return m.Footer
	}
	return nil
}

type InvokeFunctionReply_Header struct {
	Error                []byte                                       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Handled              bool                                         `protobuf:"varint,2,opt,name=handled,proto3" json:"handled,omitempty"`
	StatusCode           string                                       `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers              map[string]*InvokeFunctionReply_Header_Value `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MaxMemUsageInBytes   int64                                        `protobuf:"varint,5,opt,name=max_mem_usage_in_bytes,json=maxMemUsageInBytes,proto3" json:"max_mem_usage_in_bytes,omitempty"`
	FunctionLog          string                                       `protobuf:"bytes,6,opt,name=function_log,json=functionLog,proto3" json:"function_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *InvokeFunctionReply_Header) Reset()         { *m = InvokeFunctionReply_Header{} }
func (m *InvokeFunctionReply_Header) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply_Header) ProtoMessage()    {}
func (*InvokeFunctionReply_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{6, 0}
}

func (m *InvokeFunctionReply_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply_Header.Unmarshal(m, b)
}
func (m *InvokeFunctionReply_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply_Header.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply_Header.Merge(m, src)
}
func (m *InvokeFunctionReply_Header) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply_Header.Size(m)
}
func (m *InvokeFunctionReply_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply_Header.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply_Header proto.InternalMessageInfo

func (m *InvokeFunctionReply_Header) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *InvokeFunctionReply_Header) GetHandled() bool {
	if m != nil {
		return m.Handled
	}
	return false
}

func (m *InvokeFunctionReply_Header) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *InvokeFunctionReply_Header) GetHeaders() map[string]*InvokeFunctionReply_Header_Value {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *InvokeFunctionReply_Header) GetMaxMemUsageInBytes() int64 {
	if m != nil {
		return m.MaxMemUsageInBytes
	}
	return 0
}

func (m *InvokeFunctionReply_Header) GetFunctionLog() string {
	if m != nil {
		return m.FunctionLog
	}
	return ""
}

type InvokeFunctionReply_Header_Value struct {
	Items                []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeFunctionReply_Header_Value) Reset()         { *m = InvokeFunctionReply_Header_Value{} }
func (m *InvokeFunctionReply_Header_Value) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply_Header_Value) ProtoMessage()    {}
func (*InvokeFunctionReply_Header_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{6, 0, 0}
}

func (m *InvokeFunctionReply_Header_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply_Header_Value.Unmarshal(m, b)
}
func (m *InvokeFunctionReply_Header_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply_Header_Value.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply_Header_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply_Header_Value.Merge(m, src)
}
func (m *InvokeFunctionReply_Header_Value) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply_Header_Value.Size(m)
}
func (m *InvokeFunctionReply_Header_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply_Header_Value.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply_Header_Value proto.InternalMessageInfo

func (m *InvokeFunctionReply_Header_Value) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type InvokeFunctionReply_Footer struct {
	DurationInNanos      int64    `protobuf:"varint,1,opt,name=duration_in_nanos,json=durationInNanos,proto3" json:"duration_in_nanos,omitempty"`
	InvokeException      string   `protobuf:"bytes,2,opt,name=invoke_exception,json=invokeException,proto3" json:"invoke_exception,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeFunctionReply_Footer) Reset()         { *m = InvokeFunctionReply_Footer{} }
func (m *InvokeFunctionReply_Footer) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply_Footer) ProtoMessage()    {}
func (*InvokeFunctionReply_Footer) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{6, 1}
}

func (m *InvokeFunctionReply_Footer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply_Footer.Unmarshal(m, b)
}
func (m *InvokeFunctionReply_Footer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply_Footer.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply_Footer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply_Footer.Merge(m, src)
}
func (m *InvokeFunctionReply_Footer) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply_Footer.Size(m)
}
func (m *InvokeFunctionReply_Footer) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply_Footer.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply_Footer proto.InternalMessageInfo

func (m *InvokeFunctionReply_Footer) GetDurationInNanos() int64 {
	if m != nil {
		return m.DurationInNanos
	}
	return 0
}

func (m *InvokeFunctionReply_Footer) GetInvokeException() string {
	if m != nil {
		return m.InvokeException
	}
	return ""
}

func (m *InvokeFunctionReply_Footer) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NodeStats struct {
	TotalMemoryInBytes   int64    `protobuf:"varint,1,opt,name=total_memory_in_bytes,json=totalMemoryInBytes,proto3" json:"total_memory_in_bytes,omitempty"`
	MemoryUsageInBytes   int64    `protobuf:"varint,2,opt,name=memory_usage_in_bytes,json=memoryUsageInBytes,proto3" json:"memory_usage_in_bytes,omitempty"`
	CpuUsagePct          int64    `protobuf:"varint,3,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	DiskTotalInBytes     int64    `protobuf:"varint,4,opt,name=disk_total_in_bytes,json=diskTotalInBytes,proto3" json:"disk_total_in_bytes,omitempty"`
	DiskAvailInBytes     int64    `protobuf:"varint,5,opt,name=disk_avail_in_bytes,json=diskAvailInBytes,proto3" json:"disk_avail_in_bytes,omitempty"`
	DiskTotalInodes      int64    `protobuf:"varint,6,opt,name=disk_total_inodes,json=diskTotalInodes,proto3" json:"disk_total_inodes,omitempty"`
	DiskFreeInodes       int64    `protobuf:"varint,7,opt,name=disk_free_inodes,json=diskFreeInodes,proto3" json:"disk_free_inodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeStats) Reset()         { *m = NodeStats{} }
func (m *NodeStats) String() string { return proto.CompactTextString(m) }
func (*NodeStats) ProtoMessage()    {}
func (*NodeStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{7}
}

func (m *NodeStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeStats.Unmarshal(m, b)
}
func (m *NodeStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeStats.Marshal(b, m, deterministic)
}
func (m *NodeStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStats.Merge(m, src)
}
func (m *NodeStats) XXX_Size() int {
	return xxx_messageInfo_NodeStats.Size(m)
}
func (m *NodeStats) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStats.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStats proto.InternalMessageInfo

func (m *NodeStats) GetTotalMemoryInBytes() int64 {
	if m != nil {
		return m.TotalMemoryInBytes
	}
	return 0
}

func (m *NodeStats) GetMemoryUsageInBytes() int64 {
	if m != nil {
		return m.MemoryUsageInBytes
	}
	return 0
}

func (m *NodeStats) GetCpuUsagePct() int64 {
	if m != nil {
		return m.CpuUsagePct
	}
	return 0
}

func (m *NodeStats) GetDiskTotalInBytes() int64 {
	if m != nil {
		return m.DiskTotalInBytes
	}
	return 0
}

func (m *NodeStats) GetDiskAvailInBytes() int64 {
	if m != nil {
		return m.DiskAvailInBytes
	}
	return 0
}

func (m *NodeStats) GetDiskTotalInodes() int64 {
	if m != nil {
		return m.DiskTotalInodes
	}
	return 0
}

func (m *NodeStats) GetDiskFreeInodes() int64 {
	if m != nil {
		return m.DiskFreeInodes
	}
	return 0
}

type ContainerStats struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	TotalMemoryInBytes   int64    `protobuf:"varint,2,opt,name=total_memory_in_bytes,json=totalMemoryInBytes,proto3" json:"total_memory_in_bytes,omitempty"`
	MemoryUsageInBytes   int64    `protobuf:"varint,3,opt,name=memory_usage_in_bytes,json=memoryUsageInBytes,proto3" json:"memory_usage_in_bytes,omitempty"`
	CpuUsagePct          int64    `protobuf:"varint,4,opt,name=cpu_usage_pct,json=cpuUsagePct,proto3" json:"cpu_usage_pct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerStats) Reset()         { *m = ContainerStats{} }
func (m *ContainerStats) String() string { return proto.CompactTextString(m) }
func (*ContainerStats) ProtoMessage()    {}
func (*ContainerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{8}
}

func (m *ContainerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerStats.Unmarshal(m, b)
}
func (m *ContainerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerStats.Marshal(b, m, deterministic)
}
func (m *ContainerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerStats.Merge(m, src)
}
func (m *ContainerStats) XXX_Size() int {
	return xxx_messageInfo_ContainerStats.Size(m)
}
func (m *ContainerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerStats.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerStats proto.InternalMessageInfo

func (m *ContainerStats) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *ContainerStats) GetTotalMemoryInBytes() int64 {
	if m != nil {
		return m.TotalMemoryInBytes
	}
	return 0
}

func (m *ContainerStats) GetMemoryUsageInBytes() int64 {
	if m != nil {
		return m.MemoryUsageInBytes
	}
	return 0
}

func (m *ContainerStats) GetCpuUsagePct() int64 {
	if m != nil {
		return m.CpuUsagePct
	}
	return 0
}

type GetStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatsRequest) Reset()         { *m = GetStatsRequest{} }
func (m *GetStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatsRequest) ProtoMessage()    {}
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{9}
}

func (m *GetStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsRequest.Unmarshal(m, b)
}
func (m *GetStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsRequest.Marshal(b, m, deterministic)
}
func (m *GetStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsRequest.Merge(m, src)
}
func (m *GetStatsRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatsRequest.Size(m)
}
func (m *GetStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsRequest proto.InternalMessageInfo

type GetStatsReply struct {
	NodeStats            *NodeStats        `protobuf:"bytes,1,opt,name=node_stats,json=nodeStats,proto3" json:"node_stats,omitempty"`
	ContainerStatsList   []*ContainerStats `protobuf:"bytes,2,rep,name=container_stats_list,json=containerStatsList,proto3" json:"container_stats_list,omitempty"`
	LiveId               string            `protobuf:"bytes,3,opt,name=live_id,json=liveId,proto3" json:"live_id,omitempty"`
	OwnerAccountId       string            `protobuf:"bytes,4,opt,name=owner_account_id,json=ownerAccountId,proto3" json:"owner_account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStatsReply) Reset()         { *m = GetStatsReply{} }
func (m *GetStatsReply) String() string { return proto.CompactTextString(m) }
func (*GetStatsReply) ProtoMessage()    {}
func (*GetStatsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_59f14638aa483493, []int{10}
}

func (m *GetStatsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatsReply.Unmarshal(m, b)
}
func (m *GetStatsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatsReply.Marshal(b, m, deterministic)
}
func (m *GetStatsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatsReply.Merge(m, src)
}
func (m *GetStatsReply) XXX_Size() int {
	return xxx_messageInfo_GetStatsReply.Size(m)
}
func (m *GetStatsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatsReply proto.InternalMessageInfo

func (m *GetStatsReply) GetNodeStats() *NodeStats {
	if m != nil {
		return m.NodeStats
	}
	return nil
}

func (m *GetStatsReply) GetContainerStatsList() []*ContainerStats {
	if m != nil {
		return m.ContainerStatsList
	}
	return nil
}

func (m *GetStatsReply) GetLiveId() string {
	if m != nil {
		return m.LiveId
	}
	return ""
}

func (m *GetStatsReply) GetOwnerAccountId() string {
	if m != nil {
		return m.OwnerAccountId
	}
	return ""
}

func init() {
	proto.RegisterType((*FunctionMeta)(nil), "nodeservoceproto.FunctionMeta")
	proto.RegisterType((*CreateContainerRequest)(nil), "nodeservoceproto.CreateContainerRequest")
	proto.RegisterType((*CreateContainerReply)(nil), "nodeservoceproto.CreateContainerReply")
	proto.RegisterType((*RemoveContainerRequest)(nil), "nodeservoceproto.RemoveContainerRequest")
	proto.RegisterType((*RemoveContainerReply)(nil), "nodeservoceproto.RemoveContainerReply")
	proto.RegisterType((*InvokeFunctionRequest)(nil), "nodeservoceproto.InvokeFunctionRequest")
	proto.RegisterType((*InvokeFunctionReply)(nil), "nodeservoceproto.InvokeFunctionReply")
	proto.RegisterType((*InvokeFunctionReply_Header)(nil), "nodeservoceproto.InvokeFunctionReply.Header")
	proto.RegisterMapType((map[string]*InvokeFunctionReply_Header_Value)(nil), "nodeservoceproto.InvokeFunctionReply.Header.HeadersEntry")
	proto.RegisterType((*InvokeFunctionReply_Header_Value)(nil), "nodeservoceproto.InvokeFunctionReply.Header.Value")
	proto.RegisterType((*InvokeFunctionReply_Footer)(nil), "nodeservoceproto.InvokeFunctionReply.Footer")
	proto.RegisterType((*NodeStats)(nil), "nodeservoceproto.NodeStats")
	proto.RegisterType((*ContainerStats)(nil), "nodeservoceproto.ContainerStats")
	proto.RegisterType((*GetStatsRequest)(nil), "nodeservoceproto.GetStatsRequest")
	proto.RegisterType((*GetStatsReply)(nil), "nodeservoceproto.GetStatsReply")
}

func init() {
	proto.RegisterFile("node_service.proto", fileDescriptor_59f14638aa483493)
}

var fileDescriptor_59f14638aa483493 = []byte{
	// 955 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4f, 0x73, 0xdb, 0x44,
	0x14, 0x8f, 0x2c, 0xdb, 0xa9, 0x9f, 0xed, 0x38, 0xdd, 0xa6, 0xc1, 0x63, 0xa6, 0xd4, 0x15, 0x43,
	0x31, 0x0c, 0x64, 0xc0, 0x5c, 0x68, 0x6f, 0x25, 0x34, 0xd4, 0x33, 0x4d, 0xa6, 0xb3, 0x01, 0x0e,
	0x5c, 0x34, 0x1b, 0xe9, 0x25, 0xd5, 0x44, 0xda, 0x35, 0xd2, 0xca, 0xc4, 0xdf, 0x82, 0x19, 0xb8,
	0xf2, 0x2d, 0xb8, 0x72, 0xe2, 0xc4, 0xd7, 0xe0, 0x93, 0x30, 0xfb, 0x47, 0xb6, 0x23, 0x19, 0x62,
	0x0f, 0x27, 0x6b, 0x7f, 0xef, 0xdf, 0xef, 0xfd, 0xd9, 0xb7, 0x06, 0xc2, 0x45, 0x88, 0x7e, 0x86,
	0xe9, 0x2c, 0x0a, 0xf0, 0x68, 0x9a, 0x0a, 0x29, 0xc8, 0xbe, 0xc2, 0x14, 0x24, 0x02, 0xd4, 0x88,
	0xf7, 0x9b, 0x03, 0x9d, 0x93, 0x9c, 0x07, 0x32, 0x12, 0xfc, 0x14, 0x25, 0x23, 0xef, 0x43, 0xf7,
	0xd2, 0x9e, 0x7d, 0xce, 0x12, 0xec, 0x3b, 0x43, 0x67, 0xd4, 0xa2, 0x9d, 0x02, 0x3c, 0x63, 0x09,
	0x92, 0x3e, 0xec, 0xbe, 0x65, 0x3c, 0x8c, 0x31, 0xed, 0xd7, 0xb4, 0xb8, 0x38, 0x92, 0xa7, 0xd0,
	0x93, 0x51, 0x82, 0x22, 0x97, 0x7e, 0xc4, 0xfd, 0x0c, 0x83, 0xac, 0xef, 0x0e, 0x9d, 0x51, 0x83,
	0x76, 0x2d, 0x3c, 0xe1, 0xe7, 0x18, 0x64, 0x4a, 0x2f, 0xc1, 0x44, 0xa4, 0x73, 0xa5, 0x76, 0x31,
	0x97, 0x98, 0xf5, 0xeb, 0x43, 0x67, 0xe4, 0xd2, 0xae, 0x81, 0x27, 0xfc, 0x2b, 0x05, 0x7a, 0x3f,
	0x3b, 0x70, 0x78, 0x9c, 0x22, 0x93, 0x78, 0x2c, 0xb8, 0x64, 0x11, 0xc7, 0x94, 0xe2, 0x8f, 0x39,
	0x66, 0x92, 0x10, 0xa8, 0xaf, 0x10, 0xd4, 0xdf, 0xe4, 0x78, 0x85, 0x7d, 0x82, 0x92, 0x69, 0x7a,
	0xed, 0xf1, 0x7b, 0x47, 0xe5, 0xc4, 0x8f, 0x56, 0x93, 0x5e, 0x66, 0xa7, 0x4b, 0xf0, 0x08, 0x20,
	0x35, 0x31, 0xfc, 0x28, 0xd4, 0xf4, 0x5b, 0xb4, 0x65, 0x91, 0x49, 0xe8, 0x3d, 0x83, 0x83, 0x0a,
	0xa3, 0x69, 0x3c, 0x27, 0x4f, 0xa0, 0x13, 0x14, 0x88, 0x32, 0x34, 0xbc, 0xda, 0x0b, 0x6c, 0x12,
	0x7a, 0x3f, 0xc0, 0x21, 0xc5, 0x44, 0xcc, 0xaa, 0xc9, 0xdc, 0x6d, 0x5c, 0xa2, 0x55, 0x2b, 0xd3,
	0x3a, 0x84, 0x83, 0x8a, 0xef, 0x69, 0x3c, 0xf7, 0x7e, 0x77, 0xe0, 0xe1, 0x84, 0xcf, 0xc4, 0x35,
	0x16, 0x29, 0x6f, 0x11, 0xf3, 0x00, 0x1a, 0x38, 0x43, 0x2e, 0x75, 0xb8, 0x0e, 0x35, 0x87, 0x6a,
	0x95, 0xdd, 0xff, 0x5d, 0xe5, 0x7a, 0x39, 0x9d, 0x3f, 0x1b, 0xf0, 0xa0, 0x4c, 0x5b, 0x55, 0x99,
	0x40, 0xfd, 0x42, 0x84, 0x73, 0x4d, 0xb6, 0x43, 0xf5, 0x37, 0xf9, 0x1a, 0x9a, 0x6f, 0x91, 0x85,
	0x76, 0x1a, 0xdb, 0xe3, 0x4f, 0xaa, 0x44, 0xd6, 0xb8, 0x3a, 0x7a, 0xa5, 0x6d, 0xa8, 0xb5, 0x55,
	0x5e, 0x2e, 0x85, 0x90, 0x98, 0xda, 0x74, 0x36, 0xf4, 0x72, 0xa2, 0x6d, 0xa8, 0xb5, 0x1d, 0xfc,
	0xea, 0x42, 0xd3, 0x38, 0xd6, 0xc5, 0x4b, 0x53, 0x91, 0x5a, 0xae, 0xe6, 0xb0, 0xbc, 0x3b, 0xa6,
	0x87, 0xf7, 0x8a, 0xbb, 0x13, 0x92, 0xc7, 0xd0, 0xce, 0x24, 0x93, 0x79, 0xe6, 0x07, 0x22, 0x44,
	0x3b, 0x78, 0x60, 0xa0, 0x63, 0x11, 0x22, 0x39, 0x87, 0x5d, 0xc3, 0x55, 0x5d, 0x16, 0x77, 0xd4,
	0x1e, 0x3f, 0xdb, 0x26, 0x51, 0xfb, 0x93, 0xbd, 0xe4, 0x32, 0x9d, 0xd3, 0xc2, 0x13, 0x19, 0xc3,
	0x61, 0xc2, 0x6e, 0xfc, 0x04, 0x13, 0x3f, 0xcf, 0xd8, 0x15, 0x2e, 0x2f, 0x64, 0x43, 0x5f, 0x48,
	0x92, 0xb0, 0x9b, 0x53, 0x4c, 0xbe, 0x53, 0x32, 0x7b, 0x2b, 0xd5, 0xe4, 0x2c, 0x06, 0x20, 0x16,
	0x57, 0xfd, 0xa6, 0x99, 0x9c, 0x02, 0x7b, 0x2d, 0xae, 0x06, 0x8f, 0xa0, 0xf1, 0x3d, 0x8b, 0x73,
	0x54, 0x55, 0x88, 0x24, 0x26, 0x59, 0xdf, 0x19, 0xba, 0xa3, 0x16, 0x35, 0x87, 0x01, 0x87, 0xce,
	0x2a, 0x1d, 0xb2, 0x0f, 0xee, 0x35, 0xce, 0xed, 0x08, 0xaa, 0x4f, 0xf2, 0x0a, 0x1a, 0x33, 0xe5,
	0xc0, 0xf6, 0x74, 0xbc, 0x55, 0xaa, 0x3a, 0x34, 0x35, 0x0e, 0x9e, 0xd7, 0xbe, 0x74, 0x06, 0x39,
	0x34, 0x4d, 0xa3, 0xc8, 0xc7, 0x70, 0x3f, 0xcc, 0x53, 0xa6, 0xb9, 0x47, 0x6a, 0xc7, 0x71, 0x91,
	0xe9, 0xb8, 0x2e, 0xed, 0x15, 0x82, 0x09, 0x3f, 0x53, 0x30, 0xf9, 0x08, 0xf6, 0x23, 0x1d, 0xc4,
	0xc7, 0x9b, 0x00, 0xa7, 0x4a, 0x64, 0x2f, 0x5e, 0xcf, 0xe0, 0x2f, 0x0b, 0x78, 0xd9, 0x6c, 0xd3,
	0x36, 0x73, 0xf0, 0xfe, 0xaa, 0x41, 0xeb, 0x4c, 0x84, 0x78, 0x2e, 0x99, 0xcc, 0xc8, 0xe7, 0xf0,
	0x50, 0x0a, 0xc9, 0x62, 0xbf, 0xbc, 0xfa, 0x4c, 0x78, 0xa2, 0x85, 0xa7, 0xab, 0xfb, 0x4f, 0x99,
	0x58, 0xe5, 0x52, 0x73, 0x6a, 0xb6, 0x39, 0x5a, 0x78, 0xab, 0x39, 0x1e, 0x74, 0x83, 0x69, 0x6e,
	0xf5, 0xa7, 0x81, 0xd4, 0x8c, 0x5c, 0xda, 0x0e, 0xa6, 0xb9, 0xd6, 0x7b, 0x13, 0x48, 0xf2, 0x29,
	0x3c, 0x08, 0xa3, 0xec, 0xda, 0x37, 0x74, 0x4a, 0x2b, 0x78, 0x5f, 0x89, 0xbe, 0x55, 0x92, 0xc2,
	0x65, 0xa1, 0xce, 0x66, 0x2c, 0x8a, 0xcb, 0x03, 0xa2, 0xd5, 0x5f, 0x28, 0x49, 0xa1, 0xae, 0x4a,
	0xbc, 0xea, 0x5d, 0x35, 0x4e, 0xcf, 0x88, 0x2a, 0xf1, 0xd2, 0xb7, 0x82, 0xc9, 0x08, 0xb4, 0xbd,
	0x7f, 0x99, 0x22, 0x16, 0xaa, 0xbb, 0x5a, 0x75, 0x4f, 0xe1, 0x27, 0x29, 0xa2, 0xd1, 0xf4, 0xfe,
	0x70, 0x60, 0x6f, 0xb1, 0xdb, 0x4c, 0x41, 0x37, 0xd8, 0x60, 0xff, 0x5a, 0xf3, 0xda, 0xf6, 0x35,
	0x77, 0x37, 0xaf, 0x79, 0xbd, 0x52, 0x73, 0xef, 0x3e, 0xf4, 0xbe, 0x41, 0xa9, 0x89, 0xdb, 0x0d,
	0xec, 0xfd, 0xed, 0x40, 0x77, 0x89, 0xa9, 0xf5, 0xf6, 0x1c, 0xc0, 0xbc, 0xdb, 0x0a, 0xd2, 0xf9,
	0xb4, 0xc7, 0xef, 0x56, 0x47, 0x7f, 0x31, 0x53, 0xb4, 0xc5, 0x17, 0xe3, 0x45, 0xe1, 0x60, 0x59,
	0x0d, 0xed, 0xc0, 0x8f, 0xa3, 0x4c, 0xed, 0x6e, 0xb5, 0x2b, 0x86, 0x55, 0x2f, 0xb7, 0xab, 0x49,
	0x49, 0x70, 0xeb, 0xfc, 0x3a, 0xca, 0x24, 0x79, 0x07, 0x76, 0xe3, 0x68, 0x86, 0xcb, 0x87, 0xb0,
	0xa9, 0x8e, 0x93, 0x50, 0xf5, 0x4d, 0xfc, 0xa4, 0x02, 0xb1, 0x20, 0x10, 0x39, 0x5f, 0x59, 0xe2,
	0x7b, 0x1a, 0x7f, 0x61, 0xe0, 0x49, 0x38, 0xfe, 0xc5, 0x85, 0xb6, 0xe6, 0x6b, 0xfe, 0x8a, 0x10,
	0x84, 0x5e, 0xe9, 0xfd, 0x24, 0xa3, 0x35, 0xdc, 0xd6, 0x3e, 0xfa, 0x83, 0xa7, 0x1b, 0x68, 0xaa,
	0x57, 0x6f, 0x47, 0x85, 0x29, 0xbd, 0x87, 0xeb, 0xc2, 0xac, 0x7f, 0x8e, 0xd7, 0x85, 0x59, 0xfb,
	0xb8, 0xee, 0x90, 0x10, 0xf6, 0x6e, 0xef, 0x21, 0xf2, 0xe1, 0xdd, 0x9b, 0xca, 0x04, 0xf9, 0x60,
	0xa3, 0x95, 0xe6, 0xed, 0x7c, 0xe6, 0x90, 0x37, 0x70, 0xaf, 0x98, 0x13, 0xf2, 0xa4, 0x6a, 0x56,
	0x9a, 0xab, 0xc1, 0xe3, 0xff, 0x52, 0xd1, 0x3e, 0x2f, 0x9a, 0x1a, 0xfe, 0xe2, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x07, 0x60, 0xff, 0xc7, 0x27, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeServiceClient interface {
	CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerReply, error)
	RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerReply, error)
	InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (NodeService_InvokeFunctionClient, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsReply, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) CreateContainer(ctx context.Context, in *CreateContainerRequest, opts ...grpc.CallOption) (*CreateContainerReply, error) {
	out := new(CreateContainerReply)
	err := c.cc.Invoke(ctx, "/nodeservoceproto.NodeService/CreateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveContainer(ctx context.Context, in *RemoveContainerRequest, opts ...grpc.CallOption) (*RemoveContainerReply, error) {
	out := new(RemoveContainerReply)
	err := c.cc.Invoke(ctx, "/nodeservoceproto.NodeService/RemoveContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (NodeService_InvokeFunctionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeService_serviceDesc.Streams[0], "/nodeservoceproto.NodeService/InvokeFunction", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeServiceInvokeFunctionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodeService_InvokeFunctionClient interface {
	Recv() (*InvokeFunctionReply, error)
	grpc.ClientStream
}

type nodeServiceInvokeFunctionClient struct {
	grpc.ClientStream
}

func (x *nodeServiceInvokeFunctionClient) Recv() (*InvokeFunctionReply, error) {
	m := new(InvokeFunctionReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsReply, error) {
	out := new(GetStatsReply)
	err := c.cc.Invoke(ctx, "/nodeservoceproto.NodeService/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
type NodeServiceServer interface {
	CreateContainer(context.Context, *CreateContainerRequest) (*CreateContainerReply, error)
	RemoveContainer(context.Context, *RemoveContainerRequest) (*RemoveContainerReply, error)
	InvokeFunction(*InvokeFunctionRequest, NodeService_InvokeFunctionServer) error
	GetStats(context.Context, *GetStatsRequest) (*GetStatsReply, error)
}

// UnimplementedNodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (*UnimplementedNodeServiceServer) CreateContainer(ctx context.Context, req *CreateContainerRequest) (*CreateContainerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}
func (*UnimplementedNodeServiceServer) RemoveContainer(ctx context.Context, req *RemoveContainerRequest) (*RemoveContainerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveContainer not implemented")
}
func (*UnimplementedNodeServiceServer) InvokeFunction(req *InvokeFunctionRequest, srv NodeService_InvokeFunctionServer) error {
	return status.Errorf(codes.Unimplemented, "method InvokeFunction not implemented")
}
func (*UnimplementedNodeServiceServer) GetStats(ctx context.Context, req *GetStatsRequest) (*GetStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservoceproto.NodeService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).CreateContainer(ctx, req.(*CreateContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservoceproto.NodeService/RemoveContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveContainer(ctx, req.(*RemoveContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_InvokeFunction_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeFunctionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).InvokeFunction(m, &nodeServiceInvokeFunctionServer{stream})
}

type NodeService_InvokeFunctionServer interface {
	Send(*InvokeFunctionReply) error
	grpc.ServerStream
}

type nodeServiceInvokeFunctionServer struct {
	grpc.ServerStream
}

func (x *nodeServiceInvokeFunctionServer) Send(m *InvokeFunctionReply) error {
	return x.ServerStream.SendMsg(m)
}

func _NodeService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nodeservoceproto.NodeService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "nodeservoceproto.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _NodeService_CreateContainer_Handler,
		},
		{
			MethodName: "RemoveContainer",
			Handler:    _NodeService_RemoveContainer_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _NodeService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InvokeFunction",
			Handler:       _NodeService_InvokeFunction_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "node_service.proto",
}
