// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api_server.proto

package apiserverproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvokeFunctionRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FunctionName         string   `protobuf:"bytes,3,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Event                []byte   `protobuf:"bytes,4,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeFunctionRequest) Reset()         { *m = InvokeFunctionRequest{} }
func (m *InvokeFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionRequest) ProtoMessage()    {}
func (*InvokeFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{0}
}

func (m *InvokeFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionRequest.Unmarshal(m, b)
}
func (m *InvokeFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionRequest.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionRequest.Merge(m, src)
}
func (m *InvokeFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionRequest.Size(m)
}
func (m *InvokeFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionRequest proto.InternalMessageInfo

func (m *InvokeFunctionRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *InvokeFunctionRequest) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

type InvokeFunctionReply struct {
	RequestId             string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Body                  []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	ServerSideLatencyInMs int64    `protobuf:"varint,3,opt,name=server_side_latency_in_ms,json=serverSideLatencyInMs,proto3" json:"server_side_latency_in_ms,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *InvokeFunctionReply) Reset()         { *m = InvokeFunctionReply{} }
func (m *InvokeFunctionReply) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply) ProtoMessage()    {}
func (*InvokeFunctionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{1}
}

func (m *InvokeFunctionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply.Unmarshal(m, b)
}
func (m *InvokeFunctionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply.Merge(m, src)
}
func (m *InvokeFunctionReply) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply.Size(m)
}
func (m *InvokeFunctionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply proto.InternalMessageInfo

func (m *InvokeFunctionReply) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *InvokeFunctionReply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *InvokeFunctionReply) GetServerSideLatencyInMs() int64 {
	if m != nil {
		return m.ServerSideLatencyInMs
	}
	return 0
}

type ListFunctionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFunctionsRequest) Reset()         { *m = ListFunctionsRequest{} }
func (m *ListFunctionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListFunctionsRequest) ProtoMessage()    {}
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{2}
}

func (m *ListFunctionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFunctionsRequest.Unmarshal(m, b)
}
func (m *ListFunctionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFunctionsRequest.Marshal(b, m, deterministic)
}
func (m *ListFunctionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFunctionsRequest.Merge(m, src)
}
func (m *ListFunctionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListFunctionsRequest.Size(m)
}
func (m *ListFunctionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFunctionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFunctionsRequest proto.InternalMessageInfo

type ListFunctionsReply struct {
	Functions            []*FunctionConfig `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListFunctionsReply) Reset()         { *m = ListFunctionsReply{} }
func (m *ListFunctionsReply) String() string { return proto.CompactTextString(m) }
func (*ListFunctionsReply) ProtoMessage()    {}
func (*ListFunctionsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{3}
}

func (m *ListFunctionsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFunctionsReply.Unmarshal(m, b)
}
func (m *ListFunctionsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFunctionsReply.Marshal(b, m, deterministic)
}
func (m *ListFunctionsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFunctionsReply.Merge(m, src)
}
func (m *ListFunctionsReply) XXX_Size() int {
	return xxx_messageInfo_ListFunctionsReply.Size(m)
}
func (m *ListFunctionsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFunctionsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListFunctionsReply proto.InternalMessageInfo

func (m *ListFunctionsReply) GetFunctions() []*FunctionConfig {
	if m != nil {
		return m.Functions
	}
	return nil
}

type FunctionConfig struct {
	FunctionName         string   `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	TimeoutInSecs        int32    `protobuf:"varint,2,opt,name=timeout_in_secs,json=timeoutInSecs,proto3" json:"timeout_in_secs,omitempty"`
	MemoryInBytes        int32    `protobuf:"varint,3,opt,name=memory_in_bytes,json=memoryInBytes,proto3" json:"memory_in_bytes,omitempty"`
	Handler              string   `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionConfig) Reset()         { *m = FunctionConfig{} }
func (m *FunctionConfig) String() string { return proto.CompactTextString(m) }
func (*FunctionConfig) ProtoMessage()    {}
func (*FunctionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{4}
}

func (m *FunctionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionConfig.Unmarshal(m, b)
}
func (m *FunctionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionConfig.Marshal(b, m, deterministic)
}
func (m *FunctionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionConfig.Merge(m, src)
}
func (m *FunctionConfig) XXX_Size() int {
	return xxx_messageInfo_FunctionConfig.Size(m)
}
func (m *FunctionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionConfig proto.InternalMessageInfo

func (m *FunctionConfig) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *FunctionConfig) GetTimeoutInSecs() int32 {
	if m != nil {
		return m.TimeoutInSecs
	}
	return 0
}

func (m *FunctionConfig) GetMemoryInBytes() int32 {
	if m != nil {
		return m.MemoryInBytes
	}
	return 0
}

func (m *FunctionConfig) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func init() {
	proto.RegisterType((*InvokeFunctionRequest)(nil), "apiserverproto.InvokeFunctionRequest")
	proto.RegisterType((*InvokeFunctionReply)(nil), "apiserverproto.InvokeFunctionReply")
	proto.RegisterType((*ListFunctionsRequest)(nil), "apiserverproto.ListFunctionsRequest")
	proto.RegisterType((*ListFunctionsReply)(nil), "apiserverproto.ListFunctionsReply")
	proto.RegisterType((*FunctionConfig)(nil), "apiserverproto.FunctionConfig")
}

func init() {
	proto.RegisterFile("api_server.proto", fileDescriptor_bc0f2054e1069c43)
}

var fileDescriptor_bc0f2054e1069c43 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x75, 0x6c, 0xab, 0xe4, 0xda, 0x54, 0x19, 0x5b, 0x89, 0x05, 0xa5, 0xa4, 0x2a, 0x7d, 0xea,
	0x43, 0x7d, 0xf1, 0xc1, 0x17, 0x15, 0x84, 0x40, 0x15, 0x99, 0x3e, 0x0a, 0x86, 0x34, 0xb9, 0x75,
	0x87, 0x4d, 0x66, 0xb2, 0x99, 0x49, 0x21, 0xaf, 0xfb, 0x05, 0xfb, 0x07, 0xfb, 0x3b, 0xfb, 0x59,
	0x4b, 0x66, 0x12, 0x96, 0x64, 0x0b, 0x7d, 0xcb, 0x3d, 0xe7, 0xdc, 0xe1, 0x9c, 0x73, 0x03, 0xaf,
	0xa2, 0x9c, 0x87, 0x0a, 0x8b, 0x23, 0x16, 0xeb, 0xbc, 0x90, 0x5a, 0xd2, 0x49, 0x94, 0x73, 0x0b,
	0x98, 0xd9, 0xbf, 0x21, 0x30, 0x0b, 0xc4, 0x51, 0x5e, 0xe2, 0xcf, 0x52, 0xc4, 0x9a, 0x4b, 0xc1,
	0xf0, 0xaa, 0x44, 0xa5, 0xe9, 0x3b, 0x80, 0xc2, 0x7e, 0x86, 0x3c, 0xf1, 0xc8, 0x82, 0xac, 0x1c,
	0xe6, 0x34, 0x48, 0x90, 0xd4, 0x74, 0x14, 0xc7, 0xb2, 0x14, 0x86, 0x7e, 0x6a, 0xe9, 0x06, 0x09,
	0x12, 0xba, 0x04, 0xf7, 0xd0, 0x3c, 0x18, 0x8a, 0x28, 0x43, 0x6f, 0x60, 0x14, 0xe3, 0x16, 0xfc,
	0x1d, 0x65, 0x48, 0xa7, 0x30, 0xc2, 0x23, 0x0a, 0xed, 0x0d, 0x17, 0x64, 0x35, 0x66, 0x76, 0xf0,
	0xaf, 0x09, 0xbc, 0xee, 0x5b, 0xca, 0xd3, 0xea, 0x9c, 0x21, 0x0a, 0xc3, 0xbd, 0x4c, 0x2a, 0x63,
	0x65, 0xcc, 0xcc, 0x37, 0xfd, 0x02, 0x6f, 0x6d, 0xd8, 0x50, 0xf1, 0x04, 0xc3, 0x34, 0xd2, 0x28,
	0xe2, 0x2a, 0xe4, 0x22, 0xcc, 0x94, 0x71, 0x34, 0x60, 0x33, 0x2b, 0xd8, 0xf1, 0x04, 0xb7, 0x96,
	0x0e, 0xc4, 0x2f, 0xe5, 0xbf, 0x81, 0xe9, 0x96, 0x2b, 0xdd, 0x3a, 0x50, 0x4d, 0x2b, 0x3e, 0x03,
	0xda, 0xc3, 0x6b, 0x6b, 0x5f, 0xc1, 0x69, 0x83, 0x29, 0x8f, 0x2c, 0x06, 0xab, 0x17, 0x9b, 0xf7,
	0xeb, 0x6e, 0xd3, 0xeb, 0x76, 0xe5, 0x87, 0x14, 0x07, 0xfe, 0x9f, 0x3d, 0x2c, 0xf8, 0xb7, 0x04,
	0x26, 0x5d, 0xf6, 0x71, 0x7d, 0xe4, 0x44, 0x7d, 0x9f, 0xe0, 0xa5, 0xe6, 0x19, 0xca, 0x52, 0xd7,
	0x89, 0x14, 0xc6, 0xca, 0x84, 0x1f, 0x31, 0xb7, 0x81, 0x03, 0xb1, 0xc3, 0x58, 0xd5, 0xba, 0x0c,
	0x33, 0x59, 0x98, 0xe0, 0xfb, 0x4a, 0xa3, 0xcd, 0x3e, 0x62, 0xae, 0x85, 0x03, 0xf1, 0xbd, 0x06,
	0xa9, 0x07, 0xcf, 0x2f, 0x22, 0x91, 0xa4, 0x58, 0x98, 0x83, 0x38, 0xac, 0x1d, 0x37, 0x77, 0x04,
	0x9c, 0x6f, 0x7f, 0x82, 0x9d, 0x89, 0x43, 0xff, 0xc1, 0xa4, 0x7b, 0x1f, 0xfa, 0xb1, 0x1f, 0xf6,
	0xe4, 0x2f, 0x35, 0x5f, 0x9e, 0x93, 0xe5, 0x69, 0xe5, 0x3f, 0xa1, 0x7f, 0xc1, 0xed, 0x74, 0x4c,
	0x3f, 0xf4, 0xf7, 0x4e, 0x9d, 0x66, 0xee, 0x9f, 0x51, 0x99, 0xc7, 0xf7, 0xcf, 0x0c, 0xf7, 0xf9,
	0x3e, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xd7, 0x76, 0x4b, 0x1b, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIServerClient is the client API for APIServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServerClient interface {
	InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (*InvokeFunctionReply, error)
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsReply, error)
}

type aPIServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServerClient(cc grpc.ClientConnInterface) APIServerClient {
	return &aPIServerClient{cc}
}

func (c *aPIServerClient) InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (*InvokeFunctionReply, error) {
	out := new(InvokeFunctionReply)
	err := c.cc.Invoke(ctx, "/apiserverproto.APIServer/InvokeFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsReply, error) {
	out := new(ListFunctionsReply)
	err := c.cc.Invoke(ctx, "/apiserverproto.APIServer/ListFunctions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServerServer is the server API for APIServer service.
type APIServerServer interface {
	InvokeFunction(context.Context, *InvokeFunctionRequest) (*InvokeFunctionReply, error)
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsReply, error)
}

// UnimplementedAPIServerServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServerServer struct {
}

func (*UnimplementedAPIServerServer) InvokeFunction(ctx context.Context, req *InvokeFunctionRequest) (*InvokeFunctionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeFunction not implemented")
}
func (*UnimplementedAPIServerServer) ListFunctions(ctx context.Context, req *ListFunctionsRequest) (*ListFunctionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFunctions not implemented")
}

func RegisterAPIServerServer(s *grpc.Server, srv APIServerServer) {
	s.RegisterService(&_APIServer_serviceDesc, srv)
}

func _APIServer_InvokeFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerServer).InvokeFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserverproto.APIServer/InvokeFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerServer).InvokeFunction(ctx, req.(*InvokeFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServer_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserverproto.APIServer/ListFunctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiserverproto.APIServer",
	HandlerType: (*APIServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeFunction",
			Handler:    _APIServer_InvokeFunction_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _APIServer_ListFunctions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_server.proto",
}
