// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api_server.proto

package apiserverproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FunctionParam struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Event                []byte   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	RequestId            string   `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TimeoutInSecs        int32    `protobuf:"varint,4,opt,name=timeout_in_secs,json=timeoutInSecs,proto3" json:"timeout_in_secs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionParam) Reset()         { *m = FunctionParam{} }
func (m *FunctionParam) String() string { return proto.CompactTextString(m) }
func (*FunctionParam) ProtoMessage()    {}
func (*FunctionParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{0}
}

func (m *FunctionParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionParam.Unmarshal(m, b)
}
func (m *FunctionParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionParam.Marshal(b, m, deterministic)
}
func (m *FunctionParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionParam.Merge(m, src)
}
func (m *FunctionParam) XXX_Size() int {
	return xxx_messageInfo_FunctionParam.Size(m)
}
func (m *FunctionParam) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionParam.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionParam proto.InternalMessageInfo

func (m *FunctionParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionParam) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *FunctionParam) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *FunctionParam) GetTimeoutInSecs() int32 {
	if m != nil {
		return m.TimeoutInSecs
	}
	return 0
}

type InvokeFunctionRequest struct {
	ContainerId          string         `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Function             *FunctionParam `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InvokeFunctionRequest) Reset()         { *m = InvokeFunctionRequest{} }
func (m *InvokeFunctionRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionRequest) ProtoMessage()    {}
func (*InvokeFunctionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{1}
}

func (m *InvokeFunctionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionRequest.Unmarshal(m, b)
}
func (m *InvokeFunctionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionRequest.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionRequest.Merge(m, src)
}
func (m *InvokeFunctionRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionRequest.Size(m)
}
func (m *InvokeFunctionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionRequest proto.InternalMessageInfo

func (m *InvokeFunctionRequest) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *InvokeFunctionRequest) GetFunction() *FunctionParam {
	if m != nil {
		return m.Function
	}
	return nil
}

type InvokeFunctionReply struct {
	Body                 []byte                      `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Header               *InvokeFunctionReply_Header `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Footer               *InvokeFunctionReply_Footer `protobuf:"bytes,3,opt,name=footer,proto3" json:"footer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InvokeFunctionReply) Reset()         { *m = InvokeFunctionReply{} }
func (m *InvokeFunctionReply) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply) ProtoMessage()    {}
func (*InvokeFunctionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{2}
}

func (m *InvokeFunctionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply.Unmarshal(m, b)
}
func (m *InvokeFunctionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply.Merge(m, src)
}
func (m *InvokeFunctionReply) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply.Size(m)
}
func (m *InvokeFunctionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply proto.InternalMessageInfo

func (m *InvokeFunctionReply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *InvokeFunctionReply) GetHeader() *InvokeFunctionReply_Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *InvokeFunctionReply) GetFooter() *InvokeFunctionReply_Footer {
	if m != nil {
		return m.Footer
	}
	return nil
}

type InvokeFunctionReply_Header struct {
	Error                []byte                                       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Handled              bool                                         `protobuf:"varint,2,opt,name=handled,proto3" json:"handled,omitempty"`
	StatusCode           string                                       `protobuf:"bytes,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers              map[string]*InvokeFunctionReply_Header_Value `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DurationInNanos      int64                                        `protobuf:"varint,5,opt,name=duration_in_nanos,json=durationInNanos,proto3" json:"duration_in_nanos,omitempty"`
	MaxMemUsageInBytes   int64                                        `protobuf:"varint,6,opt,name=max_mem_usage_in_bytes,json=maxMemUsageInBytes,proto3" json:"max_mem_usage_in_bytes,omitempty"`
	FunctionLog          string                                       `protobuf:"bytes,7,opt,name=functionLog,proto3" json:"functionLog,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *InvokeFunctionReply_Header) Reset()         { *m = InvokeFunctionReply_Header{} }
func (m *InvokeFunctionReply_Header) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply_Header) ProtoMessage()    {}
func (*InvokeFunctionReply_Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{2, 0}
}

func (m *InvokeFunctionReply_Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply_Header.Unmarshal(m, b)
}
func (m *InvokeFunctionReply_Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply_Header.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply_Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply_Header.Merge(m, src)
}
func (m *InvokeFunctionReply_Header) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply_Header.Size(m)
}
func (m *InvokeFunctionReply_Header) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply_Header.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply_Header proto.InternalMessageInfo

func (m *InvokeFunctionReply_Header) GetError() []byte {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *InvokeFunctionReply_Header) GetHandled() bool {
	if m != nil {
		return m.Handled
	}
	return false
}

func (m *InvokeFunctionReply_Header) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *InvokeFunctionReply_Header) GetHeaders() map[string]*InvokeFunctionReply_Header_Value {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *InvokeFunctionReply_Header) GetDurationInNanos() int64 {
	if m != nil {
		return m.DurationInNanos
	}
	return 0
}

func (m *InvokeFunctionReply_Header) GetMaxMemUsageInBytes() int64 {
	if m != nil {
		return m.MaxMemUsageInBytes
	}
	return 0
}

func (m *InvokeFunctionReply_Header) GetFunctionLog() string {
	if m != nil {
		return m.FunctionLog
	}
	return ""
}

type InvokeFunctionReply_Header_Value struct {
	Items                []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeFunctionReply_Header_Value) Reset()         { *m = InvokeFunctionReply_Header_Value{} }
func (m *InvokeFunctionReply_Header_Value) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply_Header_Value) ProtoMessage()    {}
func (*InvokeFunctionReply_Header_Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{2, 0, 0}
}

func (m *InvokeFunctionReply_Header_Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply_Header_Value.Unmarshal(m, b)
}
func (m *InvokeFunctionReply_Header_Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply_Header_Value.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply_Header_Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply_Header_Value.Merge(m, src)
}
func (m *InvokeFunctionReply_Header_Value) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply_Header_Value.Size(m)
}
func (m *InvokeFunctionReply_Header_Value) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply_Header_Value.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply_Header_Value proto.InternalMessageInfo

func (m *InvokeFunctionReply_Header_Value) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

type InvokeFunctionReply_Footer struct {
	DurationInNanoSecs   int64    `protobuf:"varint,1,opt,name=duration_in_nano_secs,json=durationInNanoSecs,proto3" json:"duration_in_nano_secs,omitempty"`
	InvokeException      string   `protobuf:"bytes,2,opt,name=invoke_exception,json=invokeException,proto3" json:"invoke_exception,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeFunctionReply_Footer) Reset()         { *m = InvokeFunctionReply_Footer{} }
func (m *InvokeFunctionReply_Footer) String() string { return proto.CompactTextString(m) }
func (*InvokeFunctionReply_Footer) ProtoMessage()    {}
func (*InvokeFunctionReply_Footer) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{2, 1}
}

func (m *InvokeFunctionReply_Footer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeFunctionReply_Footer.Unmarshal(m, b)
}
func (m *InvokeFunctionReply_Footer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeFunctionReply_Footer.Marshal(b, m, deterministic)
}
func (m *InvokeFunctionReply_Footer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeFunctionReply_Footer.Merge(m, src)
}
func (m *InvokeFunctionReply_Footer) XXX_Size() int {
	return xxx_messageInfo_InvokeFunctionReply_Footer.Size(m)
}
func (m *InvokeFunctionReply_Footer) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeFunctionReply_Footer.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeFunctionReply_Footer proto.InternalMessageInfo

func (m *InvokeFunctionReply_Footer) GetDurationInNanoSecs() int64 {
	if m != nil {
		return m.DurationInNanoSecs
	}
	return 0
}

func (m *InvokeFunctionReply_Footer) GetInvokeException() string {
	if m != nil {
		return m.InvokeException
	}
	return ""
}

func (m *InvokeFunctionReply_Footer) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ListFunctionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFunctionsRequest) Reset()         { *m = ListFunctionsRequest{} }
func (m *ListFunctionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListFunctionsRequest) ProtoMessage()    {}
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{3}
}

func (m *ListFunctionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFunctionsRequest.Unmarshal(m, b)
}
func (m *ListFunctionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFunctionsRequest.Marshal(b, m, deterministic)
}
func (m *ListFunctionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFunctionsRequest.Merge(m, src)
}
func (m *ListFunctionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListFunctionsRequest.Size(m)
}
func (m *ListFunctionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFunctionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFunctionsRequest proto.InternalMessageInfo

type ListFunctionsReply struct {
	Functions            []*FunctionConfig `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListFunctionsReply) Reset()         { *m = ListFunctionsReply{} }
func (m *ListFunctionsReply) String() string { return proto.CompactTextString(m) }
func (*ListFunctionsReply) ProtoMessage()    {}
func (*ListFunctionsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{4}
}

func (m *ListFunctionsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFunctionsReply.Unmarshal(m, b)
}
func (m *ListFunctionsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFunctionsReply.Marshal(b, m, deterministic)
}
func (m *ListFunctionsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFunctionsReply.Merge(m, src)
}
func (m *ListFunctionsReply) XXX_Size() int {
	return xxx_messageInfo_ListFunctionsReply.Size(m)
}
func (m *ListFunctionsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFunctionsReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListFunctionsReply proto.InternalMessageInfo

func (m *ListFunctionsReply) GetFunctions() []*FunctionConfig {
	if m != nil {
		return m.Functions
	}
	return nil
}

type FunctionConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timeout              int32    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MemoryMb             int32    `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Handler              string   `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionConfig) Reset()         { *m = FunctionConfig{} }
func (m *FunctionConfig) String() string { return proto.CompactTextString(m) }
func (*FunctionConfig) ProtoMessage()    {}
func (*FunctionConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc0f2054e1069c43, []int{5}
}

func (m *FunctionConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionConfig.Unmarshal(m, b)
}
func (m *FunctionConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionConfig.Marshal(b, m, deterministic)
}
func (m *FunctionConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionConfig.Merge(m, src)
}
func (m *FunctionConfig) XXX_Size() int {
	return xxx_messageInfo_FunctionConfig.Size(m)
}
func (m *FunctionConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionConfig proto.InternalMessageInfo

func (m *FunctionConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionConfig) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *FunctionConfig) GetMemoryMb() int32 {
	if m != nil {
		return m.MemoryMb
	}
	return 0
}

func (m *FunctionConfig) GetHandler() string {
	if m != nil {
		return m.Handler
	}
	return ""
}

func init() {
	proto.RegisterType((*FunctionParam)(nil), "apiserverproto.FunctionParam")
	proto.RegisterType((*InvokeFunctionRequest)(nil), "apiserverproto.InvokeFunctionRequest")
	proto.RegisterType((*InvokeFunctionReply)(nil), "apiserverproto.InvokeFunctionReply")
	proto.RegisterType((*InvokeFunctionReply_Header)(nil), "apiserverproto.InvokeFunctionReply.Header")
	proto.RegisterMapType((map[string]*InvokeFunctionReply_Header_Value)(nil), "apiserverproto.InvokeFunctionReply.Header.HeadersEntry")
	proto.RegisterType((*InvokeFunctionReply_Header_Value)(nil), "apiserverproto.InvokeFunctionReply.Header.Value")
	proto.RegisterType((*InvokeFunctionReply_Footer)(nil), "apiserverproto.InvokeFunctionReply.Footer")
	proto.RegisterType((*ListFunctionsRequest)(nil), "apiserverproto.ListFunctionsRequest")
	proto.RegisterType((*ListFunctionsReply)(nil), "apiserverproto.ListFunctionsReply")
	proto.RegisterType((*FunctionConfig)(nil), "apiserverproto.FunctionConfig")
}

func init() {
	proto.RegisterFile("api_server.proto", fileDescriptor_bc0f2054e1069c43)
}

var fileDescriptor_bc0f2054e1069c43 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdb, 0x4e, 0xdb, 0x4a,
	0x14, 0x3d, 0x26, 0x38, 0xc1, 0x3b, 0xe1, 0x72, 0xe6, 0x00, 0xb2, 0x72, 0xc4, 0x39, 0xa9, 0x7b,
	0x51, 0xca, 0x43, 0xd4, 0xa6, 0x0f, 0xbd, 0xa8, 0x2f, 0x05, 0x81, 0x6a, 0x09, 0x2a, 0x3a, 0xa8,
	0x7d, 0xa9, 0x54, 0x6b, 0x12, 0x6f, 0xc0, 0x22, 0x9e, 0x49, 0x67, 0xc6, 0x11, 0x91, 0xfa, 0xd0,
	0xff, 0xea, 0x0f, 0xf4, 0x67, 0xfa, 0x0f, 0xd5, 0xcc, 0xd8, 0x40, 0x22, 0x2a, 0xe8, 0x93, 0xbd,
	0xd7, 0xcc, 0xda, 0xb7, 0xb5, 0xf7, 0xc0, 0x1a, 0x1b, 0x67, 0x89, 0x42, 0x39, 0x41, 0xd9, 0x1b,
	0x4b, 0xa1, 0x05, 0x59, 0x61, 0xe3, 0xcc, 0x01, 0xd6, 0x8e, 0xbe, 0x79, 0xb0, 0xbc, 0x5f, 0xf0,
	0xa1, 0xce, 0x04, 0x3f, 0x62, 0x92, 0xe5, 0x84, 0xc0, 0x22, 0x67, 0x39, 0x86, 0x5e, 0xc7, 0xeb,
	0x06, 0xd4, 0xfe, 0x93, 0x75, 0xf0, 0x71, 0x82, 0x5c, 0x87, 0x0b, 0x1d, 0xaf, 0xdb, 0xa2, 0xce,
	0x20, 0x5b, 0x00, 0x12, 0xbf, 0x14, 0xa8, 0x74, 0x92, 0xa5, 0x61, 0xcd, 0xde, 0x0f, 0x4a, 0x24,
	0x4e, 0xc9, 0x23, 0x58, 0xd5, 0x59, 0x8e, 0xa2, 0xd0, 0x49, 0xc6, 0x13, 0x85, 0x43, 0x15, 0x2e,
	0x76, 0xbc, 0xae, 0x4f, 0x97, 0x4b, 0x38, 0xe6, 0xc7, 0x38, 0x54, 0x51, 0x01, 0x1b, 0x31, 0x9f,
	0x88, 0x73, 0xac, 0xf2, 0xa0, 0xce, 0x05, 0xb9, 0x07, 0xad, 0xa1, 0xe0, 0x9a, 0x65, 0x1c, 0xa5,
	0x89, 0xe0, 0x32, 0x6a, 0x5e, 0x62, 0x71, 0x4a, 0x5e, 0xc2, 0xd2, 0x49, 0xc9, 0xb2, 0xb9, 0x35,
	0xfb, 0x5b, 0xbd, 0xd9, 0x0a, 0x7b, 0x33, 0xd5, 0xd1, 0xcb, 0xeb, 0xd1, 0x4f, 0x1f, 0xfe, 0x99,
	0x8f, 0x3b, 0x1e, 0x4d, 0x4d, 0xfd, 0x03, 0x91, 0x4e, 0x6d, 0xb4, 0x16, 0xb5, 0xff, 0x64, 0x07,
	0xea, 0x67, 0xc8, 0x52, 0x94, 0x65, 0x90, 0xed, 0xf9, 0x20, 0x37, 0x38, 0xea, 0xbd, 0xb5, 0x0c,
	0x5a, 0x32, 0x8d, 0x8f, 0x13, 0x21, 0x34, 0x4a, 0xdb, 0xa9, 0x3b, 0xfa, 0xd8, 0xb7, 0x0c, 0x5a,
	0x32, 0xdb, 0xdf, 0x6b, 0x50, 0x77, 0x6e, 0xad, 0x24, 0x52, 0x0a, 0x59, 0xe6, 0xe9, 0x0c, 0x12,
	0x42, 0xe3, 0x8c, 0xf1, 0x74, 0x84, 0xa9, 0xcd, 0x74, 0x89, 0x56, 0x26, 0xf9, 0x1f, 0x9a, 0x4a,
	0x33, 0x5d, 0xa8, 0x64, 0x28, 0x52, 0x2c, 0xd5, 0x02, 0x07, 0xed, 0x8a, 0x14, 0xc9, 0x7b, 0x68,
	0xb8, 0x4c, 0x8d, 0x4c, 0xb5, 0x6e, 0xb3, 0xff, 0xfc, 0xee, 0x45, 0x96, 0x1f, 0xb5, 0xc7, 0xb5,
	0x9c, 0xd2, 0xca, 0x0f, 0xd9, 0x86, 0xbf, 0xd3, 0x42, 0x32, 0x73, 0xdb, 0x8c, 0x00, 0x67, 0x5c,
	0xa8, 0xd0, 0xef, 0x78, 0xdd, 0x1a, 0x5d, 0xad, 0x0e, 0x62, 0xfe, 0xce, 0xc0, 0xa4, 0x0f, 0x9b,
	0x39, 0xbb, 0x48, 0x72, 0xcc, 0x93, 0x42, 0xb1, 0x53, 0x34, 0x84, 0xc1, 0x54, 0xa3, 0x0a, 0xeb,
	0x96, 0x40, 0x72, 0x76, 0x71, 0x88, 0xf9, 0x07, 0x73, 0x16, 0xf3, 0x1d, 0x73, 0x42, 0x3a, 0xd0,
	0xac, 0xe4, 0x3c, 0x10, 0xa7, 0x61, 0xc3, 0xcd, 0xc7, 0x35, 0xa8, 0xbd, 0x05, 0xfe, 0x47, 0x36,
	0x2a, 0xec, 0x04, 0x67, 0x1a, 0x73, 0x15, 0x7a, 0x9d, 0x5a, 0x37, 0xa0, 0xce, 0x68, 0x8f, 0xa0,
	0x75, 0x3d, 0x73, 0xb2, 0x06, 0xb5, 0x73, 0x9c, 0x96, 0x83, 0x66, 0x7e, 0xc9, 0x3e, 0xf8, 0x13,
	0xe3, 0xa0, 0x14, 0xfe, 0xc9, 0x1f, 0xf4, 0xc4, 0x06, 0xa6, 0x8e, 0xfe, 0x6a, 0xe1, 0x85, 0xd7,
	0xfe, 0x0a, 0x75, 0xa7, 0x27, 0x79, 0x0a, 0x1b, 0xf3, 0x8d, 0x71, 0x0b, 0xe2, 0xb9, 0x5a, 0x67,
	0x9b, 0x63, 0xb6, 0x84, 0x3c, 0x86, 0xb5, 0xcc, 0xc6, 0x4a, 0xf0, 0x62, 0x88, 0xe3, 0xcb, 0x89,
	0x0f, 0xe8, 0xaa, 0xc3, 0xf7, 0x2a, 0xf8, 0x6a, 0x34, 0x9c, 0xc8, 0xce, 0x88, 0x36, 0x61, 0xfd,
	0x20, 0x53, 0xba, 0x4a, 0x55, 0x95, 0x5b, 0x16, 0x51, 0x20, 0x73, 0xb8, 0xd9, 0x82, 0xd7, 0x10,
	0x54, 0x7d, 0x74, 0x3d, 0x6b, 0xf6, 0xff, 0xfb, 0xdd, 0x66, 0xed, 0x0a, 0x7e, 0x92, 0x9d, 0xd2,
	0x2b, 0x42, 0x54, 0xc0, 0xca, 0xec, 0xe1, 0x8d, 0xaf, 0x4a, 0x08, 0x8d, 0xf2, 0x25, 0xb0, 0x95,
	0xf8, 0xb4, 0x32, 0xc9, 0xbf, 0x10, 0xe4, 0x98, 0x0b, 0x39, 0x4d, 0xf2, 0x81, 0xad, 0xc2, 0xa7,
	0x4b, 0x0e, 0x38, 0x1c, 0x5c, 0xcd, 0xb8, 0xb4, 0xef, 0x49, 0x50, 0xcd, 0xb8, 0xec, 0xff, 0xf0,
	0x20, 0x78, 0x73, 0x14, 0x1f, 0xdb, 0x1c, 0xc9, 0x67, 0x58, 0x99, 0x55, 0x87, 0x3c, 0xbc, 0x4d,
	0x3d, 0xdb, 0x91, 0xf6, 0xfd, 0x3b, 0x88, 0x1c, 0xfd, 0x45, 0x3e, 0xc1, 0xf2, 0x4c, 0xe3, 0xc8,
	0x83, 0x79, 0xde, 0x4d, 0xfd, 0x6e, 0x47, 0xb7, 0xdc, 0xb2, 0xce, 0x07, 0x75, 0x7b, 0xf6, 0xec,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x62, 0xf5, 0xcd, 0xc6, 0xc2, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIServerClient is the client API for APIServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIServerClient interface {
	InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (*InvokeFunctionReply, error)
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsReply, error)
}

type aPIServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIServerClient(cc grpc.ClientConnInterface) APIServerClient {
	return &aPIServerClient{cc}
}

func (c *aPIServerClient) InvokeFunction(ctx context.Context, in *InvokeFunctionRequest, opts ...grpc.CallOption) (*InvokeFunctionReply, error) {
	out := new(InvokeFunctionReply)
	err := c.cc.Invoke(ctx, "/apiserverproto.APIServer/InvokeFunction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIServerClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsReply, error) {
	out := new(ListFunctionsReply)
	err := c.cc.Invoke(ctx, "/apiserverproto.APIServer/ListFunctions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServerServer is the server API for APIServer service.
type APIServerServer interface {
	InvokeFunction(context.Context, *InvokeFunctionRequest) (*InvokeFunctionReply, error)
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsReply, error)
}

// UnimplementedAPIServerServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServerServer struct {
}

func (*UnimplementedAPIServerServer) InvokeFunction(ctx context.Context, req *InvokeFunctionRequest) (*InvokeFunctionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeFunction not implemented")
}
func (*UnimplementedAPIServerServer) ListFunctions(ctx context.Context, req *ListFunctionsRequest) (*ListFunctionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFunctions not implemented")
}

func RegisterAPIServerServer(s *grpc.Server, srv APIServerServer) {
	s.RegisterService(&_APIServer_serviceDesc, srv)
}

func _APIServer_InvokeFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerServer).InvokeFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserverproto.APIServer/InvokeFunction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerServer).InvokeFunction(ctx, req.(*InvokeFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIServer_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServerServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apiserverproto.APIServer/ListFunctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServerServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _APIServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apiserverproto.APIServer",
	HandlerType: (*APIServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeFunction",
			Handler:    _APIServer_InvokeFunction_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _APIServer_ListFunctions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api_server.proto",
}
